version: '3'
services:
  web:
    image: registry.hub.docker.com/chuckdha/kubeyaml-web:latest
    ports:
    - "8000:80"
    links:
    - backend
  backend:
    image: registry.hub.docker.com/chuckdha/kubeyaml-backend:latest

